### ISSUE TITLE
Update for Kai OS

### ISSUE THREAD

**Issue by banq007** [pixma/SpotifyBox#1]
Hello! Is it possible to update this app for use in Kai OS devices?

**Comment by pixma** [comment]
Hello,

The current repo contains an unfinished project which I was developing for Firefox OS platform.
To use or to develop for Kai OS platform, it needs to be ported and should follow the guidelines provided by Kai OS Developers.

I see that one can start from here:
- https://github.com/kaiostech/sample-app

And the according to features then packages and bundles can be added to have
- daemon services, if required(to keep playing content and to show UI on lock screen)

If you think i can help you anyway, do let me know. Would like to contribute if I can contribute into KaiOS' Spotify App dev.

Annim/
